### ISSUE TITLE
CarpinchoMQ - Modo de Trabajo Publicar-Suscribir - Mensajes a todos los consumidores suscriptos disponibles

### ISSUE THREAD

**Issue by ramacal** [TP-IASC/CarpinchoMQ#13]
Metodos:
* Saber cuales son los consumidores disponibles

**Comment by dpeccia** [comment]
Para que no genere confusión, agrego un comentario que nos hizo NicoR sobre este issue:
![image](https://user-images.githubusercontent.com/42644816/143150299-8d3078ac-bba6-4243-9059-238d238406eb.png)

**Comment by dpeccia** [comment]
@facuhump2409 @ramacal dejo el estado de este ticket:
- [ ] Que la Queue tenga en el estado un elemento que indique el modo de trabajo
- [ ] Que se pueda setear el modo de trabajo `:publish_subscribe` o :`work_queue` cuando se crea la cola
- [ ] Tirar un error si el modo de trabajo que se pasa no es ninguno de los 2 mencionados
- [ ] Que cuando se pushea un nuevo mensaje a la cola, ésta le envíe a todos los consumidores el mensaje
- [ ] Que cuando los consumidores reciben el mensaje, le devuelvan a la cola un ACK
- [ ] [Deseable] Polimorfismo entre modos de trabajo junto a [este issue](https://github.com/TP-IASC/CarpinchoMQ/issues/14)
- [ ] [Fix] No tirar un error cuando el modo de trabajo no es el de los mencionados, sino devolver una tupla :error
- [ ] [Opcional] Ver si se puede mejorar el seteo del modo de trabajo al crear la cola (actualmente se crea la cola, y después se setea con una especie de setter el estado en dos pasos; ver si se puede directamente setear en la misma función que crea la cola, como pasandole en el _constructor_)
