### ISSUE TITLE
CarpinchoMQ - CRUD - Mensajes

### ISSUE THREAD

**Issue by ramacal** [TP-IASC/CarpinchoMQ#18]
(Opcional) Almacenamiento en memoria - Definir un limite a la cantidad de mensajes y/o un tamaño maximo

**Comment by dpeccia** [comment]
- Crear un mensaje está (es posible que pueda cambiar el formato)
- Para leerlos ves el estado de la cola
- No se deberia poder hacer un update en un mensaje ya creado (son inmutables)
- La eliminacion es parte de los issues de modos de trabajo

En principio cuando el Producer crea la cola pasaria el limite de cantidad de mensajes
