### ISSUE TITLE
API Administrativa - CRUD y estadisticas de Colas

### ISSUE THREAD

**Issue by CimimUxMaio** [TP-IASC/CarpinchoMQ#21]

**Comment by dpeccia** [comment]
Investigar Phoenix Framework (Front)

**Comment by CimimUxMaio** [comment]
GET /queues  (todos los nombres de las colas)
GET /queues/:nombre_cola/state (estado de una cola particular)

POST /queues (crea una cola)
POST /queues/:nombre_cola/messages (push mensaje)
