### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by CimimUxMaio** [TP-IASC/CarpinchoMQ#40]

**Comment by CimimUxMaio** [comment]
A partir de los Dockerfile de front y CarpinchoMQ

Levantamos una red de prueba.

**Comment by ramacal** [comment]
```docker-compose
version: '3.5'

networks:
  carpinchomq:
      name: iasc

services:
  carpincho-mq-a:
    container_name: carpincho-mq-a
    image: carpincho-mq-image
    hostname: carpincho-mq-a
    ports:
      - "5000:5000"
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - carpinchomq

  carpincho-mq-b:
    container_name: carpincho-mq-b
    image: carpincho-mq-image
    hostname: carpincho-mq-b
    ports:
      - "5001:5000"
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - carpinchomq

  carpincho-mq-c:
    container_name: carpincho-mq-c
    image: carpincho-mq-image
    hostname: carpincho-mq-c
    ports:
      - "5002:5000"
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - carpinchomq
     ```
Paso el docker compose y el error que me esta tirando al levnatar el segundo nodo:
![image](https://user-images.githubusercontent.com/8420859/144928292-639bb5cb-68cd-4556-a13b-f85236f7a82c.png)

 
![image](https://user-images.githubusercontent.com/8420859/144928336-f72615f2-8c57-408d-b3f4-d2f183442b7c.png)

**Comment by ramacal** [comment]
![image](https://user-images.githubusercontent.com/8420859/144928292-639bb5cb-68cd-4556-a13b-f85236f7a82c.png)

 
![image](https://user-images.githubusercontent.com/8420859/144928336-f72615f2-8c57-408d-b3f4-d2f183442b7c.png)

**Comment by ramacal** [comment]
al agregar la cookie en el parametro de conexion no lo ahce mas y si hago un connect se conectan, habria que ver algo en la logica de auto-conexion  si es qu ehay que afinar algo
